spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coderush
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 테이블 자동 갱신
    show-sql: true # 실행되는 SQL 콘솔 출력
    properties:
      hibernate:
        format_sql: true # SQL 출력 시 포맷팅
